"""
FDIS Report Export Engine
Generates PDF and PowerPoint reports.
"""
import os
import io
from datetime import datetime
from flask import current_app

from app.engine.statistics import get_team_overview, get_match_analysis, get_player_overview, get_league_table
from app.engine.nlg import generate_team_analysis, generate_match_summary, generate_player_analysis


def generate_team_report_pdf(team_id):
    """
    Generate a PDF report for a team.
    Returns bytes of the PDF file.
    """
    from fpdf import FPDF

    data = get_team_overview(team_id)
    if not data:
        return None

    analysis_text = generate_team_analysis(team_id)
    team_name = data['team']['name']

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_text_color(102, 126, 234)
    pdf.cell(0, 15, f'{team_name}', ln=True, align='C')
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, 'Performance Analysis Report', ln=True, align='C')
    pdf.cell(0, 6, f'Generated: {datetime.now().strftime("%d %B %Y")}', ln=True, align='C')
    pdf.ln(10)

    # Horizontal line
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # Key Statistics section
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, 'Key Statistics', ln=True)
    pdf.ln(3)

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(60, 60, 60)

    stats_rows = [
        ('Matches Played', str(data['matches_played'])),
        ('Record', f"{data['wins']}W / {data['draws']}D / {data['losses']}L"),
        ('Points', str(data['points'])),
        ('Win Rate', f"{data['win_rate']}%"),
        ('Goals Scored', str(data['goals_for'])),
        ('Goals Conceded', str(data['goals_against'])),
        ('Goal Difference', f"{'+' if data['goal_difference'] >= 0 else ''}{data['goal_difference']}"),
        ('Clean Sheets', str(data['clean_sheets'])),
        ('Avg Possession', f"{data['avg_possession']}%"),
        ('Avg Pass Accuracy', f"{data['avg_pass_accuracy']}%"),
        ('Avg xG', str(data['avg_xg'])),
        ('Form (Last 5)', data['form_string']),
    ]

    for i, (label, value) in enumerate(stats_rows):
        bg = i % 2 == 0
        if bg:
            pdf.set_fill_color(240, 243, 255)
        pdf.cell(90, 8, f'  {label}', border=0, fill=bg)
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(0, 8, value, ln=True, border=0, fill=bg)
        pdf.set_font('Helvetica', '', 11)

    pdf.ln(8)

    # Analysis section
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, 'Automated Analysis', ln=True)
    pdf.ln(3)

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(60, 60, 60)
    # Strip markdown bold markers for PDF
    clean_text = analysis_text.replace('**', '')
    for paragraph in clean_text.split('\n\n'):
        pdf.multi_cell(0, 6, paragraph.strip())
        pdf.ln(3)

    # Footer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, 'Report generated by Football Data Intelligence System (FDIS)', align='C')

    return pdf.output()


def generate_match_report_pdf(match_id):
    """
    Generate a PDF report for a match.
    Returns bytes of the PDF file.
    """
    from fpdf import FPDF

    analysis = get_match_analysis(match_id)
    if not analysis:
        return None

    match = analysis['match']
    summary_text = generate_match_summary(match_id)
    home = match['home_team']
    away = match['away_team']

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_text_color(102, 126, 234)
    pdf.cell(0, 15, f"{home['name']}  {match['home_goals']} - {match['away_goals']}  {away['name']}", ln=True, align='C')

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(150, 150, 150)
    date_str = match.get('date', 'Unknown date')
    league_str = match.get('league', '')
    pdf.cell(0, 7, f'{league_str} | {date_str}', ln=True, align='C')
    pdf.ln(8)

    pdf.set_draw_color(102, 126, 234)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # Stats comparison table
    hs = analysis.get('home_stats', {})
    as_ = analysis.get('away_stats', {})

    if hs and as_:
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 10, 'Match Statistics', ln=True)
        pdf.ln(3)

        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_fill_color(102, 126, 234)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(50, 8, home['name'], align='C', fill=True)
        pdf.cell(80, 8, 'Statistic', align='C', fill=True)
        pdf.cell(50, 8, away['name'], align='C', fill=True)
        pdf.ln()

        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(60, 60, 60)

        stat_rows = [
            (str(hs.get('possession', 0)), 'Possession %', str(as_.get('possession', 0))),
            (str(hs.get('total_shots', 0)), 'Total Shots', str(as_.get('total_shots', 0))),
            (str(hs.get('shots_on_target', 0)), 'Shots on Target', str(as_.get('shots_on_target', 0))),
            (str(hs.get('total_passes', 0)), 'Passes', str(as_.get('total_passes', 0))),
            (f"{hs.get('pass_accuracy', 0)}%", 'Pass Accuracy', f"{as_.get('pass_accuracy', 0)}%"),
            (str(hs.get('corners', 0)), 'Corners', str(as_.get('corners', 0))),
            (str(hs.get('fouls', 0)), 'Fouls', str(as_.get('fouls', 0))),
            (str(hs.get('yellow_cards', 0)), 'Yellow Cards', str(as_.get('yellow_cards', 0))),
            (str(hs.get('xg', 0)), 'xG', str(as_.get('xg', 0))),
        ]

        for i, (h_val, label, a_val) in enumerate(stat_rows):
            if i % 2 == 0:
                pdf.set_fill_color(245, 247, 255)
            else:
                pdf.set_fill_color(255, 255, 255)
            pdf.cell(50, 7, h_val, align='C', fill=True)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(80, 7, label, align='C', fill=True)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(50, 7, a_val, align='C', fill=True)
            pdf.ln()

    pdf.ln(8)

    # Summary
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, 'Match Summary', ln=True)
    pdf.ln(3)

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(60, 60, 60)
    clean_text = summary_text.replace('**', '')
    for paragraph in clean_text.split('\n\n'):
        pdf.multi_cell(0, 6, paragraph.strip())
        pdf.ln(3)

    # Footer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, 'Report generated by Football Data Intelligence System (FDIS)', align='C')

    return pdf.output()


def generate_team_report_pptx(team_id):
    """
    Generate a PowerPoint report for a team.
    Returns bytes of the PPTX file.
    """
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    data = get_team_overview(team_id)
    if not data:
        return None

    analysis_text = generate_team_analysis(team_id)
    team_name = data['team']['name']

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # ── Slide 1: Title ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = RGBColor(10, 14, 39)

    txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11), Inches(2))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = team_name
    p.font.size = Pt(48)
    p.font.color.rgb = RGBColor(102, 126, 234)
    p.font.bold = True
    p.alignment = PP_ALIGN.CENTER

    p2 = tf.add_paragraph()
    p2.text = 'Performance Analysis Report'
    p2.font.size = Pt(24)
    p2.font.color.rgb = RGBColor(200, 200, 200)
    p2.alignment = PP_ALIGN.CENTER

    p3 = tf.add_paragraph()
    p3.text = f'Generated: {datetime.now().strftime("%d %B %Y")}'
    p3.font.size = Pt(14)
    p3.font.color.rgb = RGBColor(150, 150, 150)
    p3.alignment = PP_ALIGN.CENTER

    # ── Slide 2: Key Stats ──
    slide2 = prs.slides.add_slide(prs.slide_layouts[6])
    slide2.background.fill.solid()
    slide2.background.fill.fore_color.rgb = RGBColor(10, 14, 39)

    title_box = slide2.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12), Inches(1))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = 'Key Statistics'
    p.font.size = Pt(32)
    p.font.color.rgb = RGBColor(102, 126, 234)
    p.font.bold = True

    stats_items = [
        (f"{data['wins']}W {data['draws']}D {data['losses']}L", 'Record'),
        (f"{data['points']}", 'Points'),
        (f"{data['win_rate']}%", 'Win Rate'),
        (f"{data['goals_for']}", 'Goals Scored'),
        (f"{data['goal_difference']:+d}", 'Goal Diff'),
        (f"{data['avg_possession']}%", 'Avg Possession'),
        (f"{data['avg_xg']}", 'Avg xG'),
        (f"{data['form_string']}", 'Form (Last 5)'),
    ]

    for i, (value, label) in enumerate(stats_items):
        col = i % 4
        row = i // 4
        x = Inches(0.5 + col * 3.2)
        y = Inches(1.6 + row * 2.5)

        box = slide2.shapes.add_textbox(x, y, Inches(2.8), Inches(2))
        tf = box.text_frame
        p = tf.paragraphs[0]
        p.text = str(value)
        p.font.size = Pt(36)
        p.font.color.rgb = RGBColor(67, 233, 123)
        p.font.bold = True
        p.alignment = PP_ALIGN.CENTER

        p2 = tf.add_paragraph()
        p2.text = label
        p2.font.size = Pt(14)
        p2.font.color.rgb = RGBColor(180, 180, 180)
        p2.alignment = PP_ALIGN.CENTER

    # ── Slide 3: Analysis ──
    slide3 = prs.slides.add_slide(prs.slide_layouts[6])
    slide3.background.fill.solid()
    slide3.background.fill.fore_color.rgb = RGBColor(10, 14, 39)

    title_box = slide3.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12), Inches(1))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = 'Analysis'
    p.font.size = Pt(32)
    p.font.color.rgb = RGBColor(102, 126, 234)
    p.font.bold = True

    clean_text = analysis_text.replace('**', '')
    text_box = slide3.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(12), Inches(5))
    tf = text_box.text_frame
    tf.word_wrap = True
    for i, paragraph in enumerate(clean_text.split('\n\n')):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.text = paragraph.strip()
        p.font.size = Pt(16)
        p.font.color.rgb = RGBColor(220, 220, 220)
        p.space_after = Pt(12)

    # Save to bytes
    output = io.BytesIO()
    prs.save(output)
    return output.getvalue()
